apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-03-18T01:24:09Z"
  generation: 1
  labels:
    run: httpbin-deployment
  name: httpbin-deployment
  namespace: test1
  resourceVersion: "311325"
  selfLink: /apis/apps/v1/namespaces/test1/deployments/httpbin-deployment
  uid: 4feef9ce-7e6d-4a28-a973-7ea3c0a49d6f
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: httpbin-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: httpbin-deployment
    spec:
      containers:
      - image: kennethreitz/httpbin
        imagePullPolicy: Always
        name: httpbin-deployment
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-03-18T01:24:09Z"
    lastUpdateTime: "2020-03-18T01:24:09Z"
    message: Created new replica set "httpbin-deployment-79f6dfbb9"
    reason: NewReplicaSetCreated
    status: "True"
    type: Progressing
