apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-03-18T13:27:16Z"
  generateName: web-
  labels:
    app: nginx
    controller-revision-hash: web-6596ffb49b
    statefulset.kubernetes.io/pod-name: web-0
  name: web-0
  namespace: test1
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: web
    uid: 5aa22e86-29df-4fc3-a75a-bc97f3cc619e
  resourceVersion: "349717"
  selfLink: /api/v1/namespaces/test1/pods/web-0
  uid: 87e30944-badb-466b-a6f9-310d35bd48d1
spec:
  containers:
  - image: k8s.gcr.io/nginx-slim:0.8
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      name: web
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-xqj2x
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: web-0
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: nginx
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: www
    persistentVolumeClaim:
      claimName: www-web-0
  - name: default-token-xqj2x
    secret:
      defaultMode: 420
      secretName: default-token-xqj2x
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-18T13:27:16Z"
    message: 'error while running "VolumeBinding" filter plugin for pod "web-0": pod
      has unbound immediate PersistentVolumeClaims'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
