apiVersion: v1
kind: Pod
metadata:
  annotations:
    newAnnotation: newAnnotationValue
  creationTimestamp: "2020-03-24T07:52:28Z"
  deletionGracePeriodSeconds: 10
  deletionTimestamp: "2020-03-25T09:09:56Z"
  generateName: web-
  labels:
    app: nginx
    controller-revision-hash: web-f96c5b685
    statefulset.kubernetes.io/pod-name: web-0
  name: web-0
  namespace: test1
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: web
    uid: a8392004-fa2e-4081-93c7-19de06e8f96c
  resourceVersion: "219639"
  selfLink: /api/v1/namespaces/test1/pods/web-0
  uid: bd5e7c1e-1d0f-43d5-bead-7a1e27348cd4
spec:
  containers:
  - image: k8s.gcr.io/nginx-slim:0.8
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      name: web
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dfmm7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: web-0
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: nginx
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: www
    persistentVolumeClaim:
      claimName: www-web-0
  - name: default-token-dfmm7
    secret:
      defaultMode: 420
      secretName: default-token-dfmm7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-24T07:52:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-03-25T02:08:18Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-03-25T02:08:18Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-03-24T07:52:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://21dd5b5b104075c7209c98fac0e0c0e507aaf18fe47aa8dba1b1fcfbbb45a14f
    image: k8s.gcr.io/nginx-slim:0.8
    imageID: docker-pullable://k8s.gcr.io/nginx-slim@sha256:8b4501fe0fe221df663c22e16539f399e89594552f400408303c42f3dd8d0e52
    lastState:
      terminated:
        containerID: docker://ade3b1f8576aa40b97917f8e7a569508b3b6e65b4a8de91ea9c398391ac019b2
        exitCode: 0
        finishedAt: "2020-03-25T02:07:56Z"
        reason: Completed
        startedAt: "2020-03-25T02:07:52Z"
    name: nginx
    ready: true
    restartCount: 2
    started: true
    state:
      running:
        startedAt: "2020-03-25T02:08:18Z"
  hostIP: 192.168.99.105
  phase: Running
  podIP: 172.17.0.4
  podIPs:
  - ip: 172.17.0.4
  qosClass: BestEffort
  startTime: "2020-03-24T07:52:28Z"
