apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-03-18T02:01:52Z"
  labels:
    run: test-pod
  name: test-pod
  namespace: test1
  resourceVersion: "316517"
  selfLink: /api/v1/namespaces/test1/pods/test-pod
  uid: 6a9dc1eb-71da-43f4-85b1-822156f3a37e
spec:
  containers:
  - image: k8s.gcr.io/pause:3.1
    imagePullPolicy: IfNotPresent
    name: test-pod
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-mq57w
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-mq57w
    secret:
      defaultMode: 420
      secretName: default-token-mq57w
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-18T02:01:52Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-03-18T02:01:55Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-03-18T02:01:55Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-03-18T02:01:52Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b930dcacd93843e5144bd11fe6a225d30dd3c23f5a1e8c190ce4a22d0150a1f3
    image: k8s.gcr.io/pause:3.1
    imageID: docker://sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e
    lastState: {}
    name: test-pod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-03-18T02:01:54Z"
  hostIP: 192.168.99.102
  phase: Running
  podIP: 172.17.0.4
  podIPs:
  - ip: 172.17.0.4
  qosClass: BestEffort
  startTime: "2020-03-18T02:01:52Z"
