apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-03-23T14:51:05Z"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeDNS
  name: kube-dns
  namespace: kube-system
  resourceVersion: "177"
  selfLink: /api/v1/namespaces/kube-system/services/kube-dns
  uid: 07ae1351-0df2-4ea5-b7d3-68fe83790681
spec:
  clusterIP: 10.96.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
endpoint:
  apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2020-03-23T14:51:05Z"
    creationTimestamp: "2020-03-23T14:51:13Z"
    labels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: KubeDNS
    name: kube-dns
    namespace: kube-system
    resourceVersion: "323847"
    selfLink: /api/v1/namespaces/kube-system/endpoints/kube-dns
    uid: f2dd279a-a79f-4097-99ef-e3c766a4221a
  subsets:
  - addresses:
    - ip: 172.17.0.5
      nodeName: minikube
      targetRef:
        kind: Pod
        name: coredns-6955765f44-8vjw8
        namespace: kube-system
        resourceVersion: "323806"
        uid: b5fba922-6dcb-4a8d-8b57-f7c01f027609
    - ip: 172.17.0.7
      nodeName: minikube
      targetRef:
        kind: Pod
        name: coredns-6955765f44-knpzb
        namespace: kube-system
        resourceVersion: "323809"
        uid: 0693c3e6-1fe4-4514-8013-53ddb1d8001b
    ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: metrics
      port: 9153
      protocol: TCP
