apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: resource-status
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/bergerx/kubectl-resource-status/releases/download/v0.1.0/resource-status_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./resource-status"
      to: "."
    bin: "resource-status"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/bergerx/kubectl-resource-status/releases/download/v0.1.0/resource-status_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./resource-status"
      to: "."
    bin: "resource-status"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/bergerx/kubectl-resource-status/releases/download/v0.1.0/resource-status_windows_amd64.zip
    sha256: ""
    files:
    - from: "/resource-status.exe"
      to: "."
    bin: "resource-status.exe"
  shortDescription: Show status details of a given resource.
  homepage: https://github.com/bergerx/kubectl-resource-status
  caveats: |
    Usage:
      $ kubectl resource-status

    For additional options:
      $ kubectl resource-status --help
      or https://github.com/bergerx/kubectl-resource-status/blob/v0.1.0/doc/USAGE.md

  description: |
    Show status details of a given resource. Doesn't work for all possible
    resource types, workload resources are mainly supported.
