apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: resource-status
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/bergerx/kubectl-resource-status/releases/download/v0.1.2/resource-status_linux_amd64.tar.gz
    sha256: "f441f485cf8984dfdba6dcd3b24a487d32cc8fcc714d2e8abbc16c374647e5e3"
    files:
    - from: "./resource-status"
      to: "."
    bin: "resource-status"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/bergerx/kubectl-resource-status/releases/download/v0.1.2/resource-status_darwin_amd64.tar.gz
    sha256: "4ae44c0cbabf0cd85249f59af38d1621546c29cc669e49529300520a14123e8c"
    files:
    - from: "./resource-status"
      to: "."
    bin: "resource-status"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/bergerx/kubectl-resource-status/releases/download/v0.1.2/resource-status_windows_amd64.zip
    sha256: "fede11f014ab553a33652733ed70f601c1468f7e085dc48a1822be0abd56ebd5"
    files:
    - from: "/resource-status.exe"
      to: "."
    bin: "resource-status.exe"
  shortDescription: Show status details of a given resource.
  homepage: https://github.com/bergerx/kubectl-resource-status
  caveats: |
    Usage:
      $ kubectl resource-status

    For additional options:
      $ kubectl resource-status --help
      or https://github.com/bergerx/kubectl-resource-status/blob/v0.1.0/doc/USAGE.md

  description: |
    Show status details of a given resource. Doesn't work for all possible
    resource types, workload resources are mainly supported.
