apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: status
spec:
  version: "v0.2.1"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/bergerx/kubectl-status/releases/download/v0.1.2/status_linux_amd64.tar.gz
    sha256: "ade0777a7fc76b986102e36c70d7e5484dd7e0649131187f6973f8e885ab2c11"
    files:
    - from: "./status"
      to: "."
    - from: LICENCE
      to: "."
    bin: "status"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/bergerx/kubectl-status/releases/download/v0.1.2/status_darwin_amd64.tar.gz
    sha256: "848e479388788e859d7d518ca4f4d0f496a8d8f39658e44f96c0411a8690e3de"
    files:
    - from: "./status"
      to: "."
    - from: LICENCE
      to: "."
    bin: "status"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/bergerx/kubectl-status/releases/download/v1.1.2/status_windows_amd64.zip
    sha256: "8fac0f8414e8dfd4b6b6a473c3106deccecac6757f244f5854636efc32bc6ab0"
    files:
    - from: "/status.exe"
      to: "."
    - from: LICENCE
      to: "."
    bin: "status.exe"
  shortDescription: Show status details of a given resource.
  homepage: https://github.com/bergerx/kubectl-status
  caveats: |
    Usage:
      $ kubectl status

    For additional options:
      $ kubectl status --help
      or https://github.com/bergerx/kubectl-status/blob/master/doc/USAGE.md

  description: |
    Show status details of a given resource. Most useful when debugging Pod issues.
